seed_everything: 333
trainer:
  gpus: 3, 4
  gradient_clip_val: 1.0
  default_root_dir: &exp_name results/gsmath-gpt_neo_125M-finetuning
  # default_root_dir: &exp_name results/debug-tmp
  val_check_interval: 1.0
  max_steps: &max_steps 50000
  # progress_bar_refresh_rate: 1
  log_every_n_steps: 1
  logger:
    - class_path: finetuning.lightning_modules.patches.patched_loggers.PatchedWandbLogger
      init_args:
        entity: yale-lily
        project: unified-codegen
        name: *exp_name
        log_model: False
        save_code: True
        offline: False
  callbacks:
    - class_path: pytorch_lightning.callbacks.model_checkpoint.ModelCheckpoint
      init_args:
        monitor: exec_acc
        mode: max
        filename: '{step}-{exec_acc:.4f}-{exec_rate:.4f}'
        save_top_k: 5
    - class_path: pytorch_lightning.callbacks.LearningRateMonitor
      init_args:
        logging_interval: step
    - class_path: pytorch_lightning.callbacks.progress.TQDMProgressBar
      init_args:
        refresh_rate: 1
    # - class_path: pytorch_lightning.callbacks.gpu_stats_monitor.GPUStatsMonitor
    #   init_args:
    #     memory_utilization: true
    #     gpu_utilization: true
        
  accelerator: gpu
  # replace_sampler_ddp: False
  # https://github.com/PyTorchLightning/pytorch-lightning/issues/8262
  # strategy: deepspeed_stage_2
  strategy: ddp_find_unused_parameters_false
  precision: 16
  # accumulate_grad_batches: 4

model:
  class_path: lightning_modules.models.seq2seq_model.Seq2SeqModel
  init_args:
    transformer_model_name: &transformer EleutherAI/gpt-neo-125M
    exec_func: execution.mathqa_execution.mathqa_execution
    answer_eq_func: execution.mathqa_execution.mathqa_answer_eq
    max_gen_len: 256
    sampling_temp: 0.2
    # sampling_temp_at_k: 0.8
    # pass_at_k: 80
    # eval_pass_at_k_every_n_epochs: 1
    # max_generation_batches: 10
    gradient_ckpt: true
    # eval_greedy_search: true
    optimizer:
      init_args: 
        lr: 1.0e-4
        # lr: 0.0
        betas: 
          - 0.9
          - 0.999
        eps: 1.0e-8
        weight_decay: 0.1
    lr_scheduler:
      name: linear
      init_args:
        num_warmup_steps: 100
        num_training_steps: *max_steps

data:
  class_path: lightning_modules.datasets.mathqa_reader.MathQADataModule
  init_args:
    transformer_model_name: *transformer
    batch_size: 1
    val_batch_size: 2
    train_file_path: data/gsmath/gsmath_train_annotated.jsonl
    val_file_path: data/gsmath/gsmath_val.jsonl
    # train_max_instances: 20
    # val_max_instances: 40
