seed_everything: 333
trainer:
  gpus: 0, 1
  gradient_clip_val: 1.0
  # default_root_dir: &exp_name results/mathqa-codet5-finetuning
  default_root_dir: &exp_name results/debug-tmp
  # val_check_interval: 1.0
  check_val_every_n_epoch: 4
  max_steps: &max_steps 100000
  # progress_bar_refresh_rate: 1
  num_sanity_val_steps: 0
  log_every_n_steps: 1
  logger+:
    - class_path: finetuning.lightning_modules.patches.patched_loggers.PatchedWandbLogger
      init_args:
        entity: niansong1996
        project: cot-codegen
        save_dir: *exp_name
        name: *exp_name
        log_model: False
        save_code: True
        offline: False
        # offline: True
  callbacks+:
    - class_path: pytorch_lightning.callbacks.model_checkpoint.ModelCheckpoint
      init_args:
        monitor: exec_acc
        # monitor: pass@100
        mode: max
        filename: '{step}-{exec_acc:.4f}-{exec_rate:.4f}'
        # filename: '{step}-{pass@100:.4f}-{exec_acc:.4f}'
        save_top_k: 3
        save_last: True
    - class_path: pytorch_lightning.callbacks.LearningRateMonitor
      init_args:
        logging_interval: step
    - class_path: pytorch_lightning.callbacks.progress.TQDMProgressBar
      init_args:
        refresh_rate: 1
        
  accelerator: gpu
  # replace_sampler_ddp: False
  # https://github.com/PyTorchLightning/pytorch-lightning/issues/8262
  # strategy: deepspeed_stage_2
  strategy: ddp_find_unused_parameters_false
  # precision: 16
  # accumulate_grad_batches: 4

model:
  class_path: lightning_modules.models.seq2seq_model.Seq2SeqModel
  init_args:
    transformer_model_name: &transformer Salesforce/codet5-base
    executor_cls: execution.executors.SpiderExecutor
    # categorize_func: execution.spider_execution.spider_categorize_complexity
    # category_list: ["JOIN", "NESTED", "COMPOUND", "SIMPLE"]
    max_gen_len: 128
    sampling_temp: 0.01
    # sampling_temp_at_k: 1.0
    # pass_at_k: 10
    # load_ckpt_file: results/spider-t5_base-finetuning-skg_data-linear_lrs-bs_32/cot-codegen/29q9irfu/checkpoints/step=12862-exec_acc=0.5742-exec_rate=0.6855.ckpt
    # eval_pass_at_k_every_n_epochs: 1
    # max_generation_batches: 10
    gradient_ckpt: true
    # eval_greedy_search: true
    optimizer:
      init_args: 
        lr: 5.0e-5
        # lr: 0.0
        betas: 
          - 0.9
          - 0.999
        eps: 1.0e-8
        weight_decay: 0.01
    lr_scheduler:
      name: linear
      init_args:
        num_warmup_steps: 100
        num_training_steps: *max_steps

data:
  class_path: lightning_modules.datasets.mathqa_reader.MathQADataModule
  init_args:
    transformer_model_name: *transformer
    batch_size: 4
    val_batch_size: 4
    train_max_instances: 200
    val_max_instances: 100
    train_set_init_args:
      file_path: data/mathqa/train-python.jsonl
    val_set_init_args:
      file_path: data/mathqa/val-python.jsonl
      # file_path: data/mathqa/val_python_with_states.jsonl
    set_common_init_args:
      use_skg_format: false