seed_everything: 333
trainer:
  gpus: 8
  gradient_clip_val: 1.0
  # default_root_dir: &exp_name results/squall-t5_large-finetuning-cat_eval-pass_100_eval-max_pass_at_k
  # default_root_dir: &exp_name results/squall-t5_large-finetuning-cat_eval-pass_100_eval-max_pass_at_k-train_eval-all_1
  # default_root_dir: &exp_name results/spider-t5_base-finetuning-skg_data-linear_lrs-bs_32
  default_root_dir: &exp_name results/debug-tmp
  # default_root_dir: &exp_name results/spider-t5_base-finetuning-skg_data-max_pass_at_100
  # val_check_interval: 1.0
  check_val_every_n_epoch: 1
  max_steps: &max_steps 25000
  # progress_bar_refresh_rate: 1
  num_sanity_val_steps: 0
  log_every_n_steps: 1
  logger+:
    - class_path: finetuning.lightning_modules.patches.patched_loggers.PatchedWandbLogger
      init_args:
        entity: niansong1996
        project: cot-codegen
        save_dir: *exp_name
        name: *exp_name
        log_model: False
        save_code: True
        offline: False
        # offline: True
  callbacks+:
    - class_path: pytorch_lightning.callbacks.model_checkpoint.ModelCheckpoint
      init_args:
        # monitor: exec_acc
        monitor: pass@100
        mode: max
        # filename: '{step}-{exec_acc:.4f}-{exec_rate:.4f}'
        filename: '{step}-{pass@100:.4f}-{exec_acc:.4f}'
        save_top_k: 3
        save_last: True
    - class_path: pytorch_lightning.callbacks.LearningRateMonitor
      init_args:
        logging_interval: step
    - class_path: pytorch_lightning.callbacks.progress.TQDMProgressBar
      init_args:
        refresh_rate: 1
    # - class_path: pytorch_lightning.callbacks.gpu_stats_monitor.GPUStatsMonitor
    #   init_args:
    #     memory_utilization: true
    #     gpu_utilization: true
        
  accelerator: gpu
  # replace_sampler_ddp: False
  # https://github.com/PyTorchLightning/pytorch-lightning/issues/8262
  strategy: deepspeed_stage_2
  # strategy: ddp_find_unused_parameters_false
  # precision: 16
  accumulate_grad_batches: 4

model:
  class_path: lightning_modules.models.seq2seq_model.Seq2SeqModel
  init_args:
    transformer_model_name: &transformer t5-3b
    executor_cls: execution.executors.SpiderExecutor
    categorize_func: execution.spider_execution.spider_categorize_complexity
    category_list: ["JOIN", "NESTED", "COMPOUND", "SIMPLE"]
    max_gen_len: 128
    sampling_temp: 0.01
    sampling_temp_at_k: 1.2
    pass_at_k: 100
    # load_ckpt_file: results/spider-t5_base-finetuning-skg_data-max_pass_at_100/cot-codegen/3d77yxxv/checkpoints/step=2616-pass@100=0.7413-exec_acc=0.5490.ckpt
    # eval_pass_at_k_every_n_epochs: 1
    max_generation_batches: 10
    # gradient_ckpt: true
    # eval_greedy_search: true
    optimizer:
      init_args: 
        lr: 5.0e-5
        # lr: 0.0
        betas: 
          - 0.9
          - 0.999
        eps: 1.0e-8
        weight_decay: 0.01
    lr_scheduler:
      name: linear
      init_args:
        num_warmup_steps: 100
        num_training_steps: *max_steps

data:
  class_path: lightning_modules.datasets.spider_reader.Text2SqlDataModule
  init_args:
    transformer_model_name: *transformer
    batch_size: 1
    val_batch_size: 2
    # train_max_instances: 100
    # val_max_instances: 100
    train_set_init_args:
      # file_path: data/squall/squall_processed_train_all.jsonl
      # file_path: data/spider/train_spider_processed_v2_db_path.jsonl
      file_path: data/spider/spider_skg_train.jsonl
    val_set_init_args:
      # file_path: data/squall/squall_processed_dev_all.jsonl
      # file_path: data/spider/dev_processed_db_path.jsonl
      file_path: data/spider/spider_skg_dev.jsonl
    set_common_init_args:
      use_skg_format: true